//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorito
    {
        public int Id { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdPlato { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Plato Plato { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
